### ISSUE TITLE
Trigger animation only once

### ISSUE THREAD

**Issue by crushy26** [stephane-monnot/react-vertical-timeline#107]
Hi,

How do I make sure the animation is not triggered every time I scroll up and down? 

I want to show only once when in view. I am using the example provided.

I checked you resume on github, it doesn't have any explicit code to achieve this, but still the timeline elements animations are triggered only once.

**Comment by crushy26** [comment]
@stephane-monnot Hey, please provide a solution. Is this is an expected behaviour?

**Comment by payapula** [comment]
Hi @crushy26 

I too checked on the code to achieve what you are expecting. Sadly, haven't yet landed on one.

However as you mentioned, resume on github does this, because it is using old version of react-vertical-timeline (v2.2.0 if I remember correctly). 

In that version, this package was dependent on [react-visibility-sensor](https://www.npmjs.com/package/react-visibility-sensor) and they migrated to [react-intersection-observer](https://www.npmjs.com/package/react-intersection-observer) lately. 

Hope it helps!

**Comment by crushy26** [comment]
Hi @payapula,

Thank you for your reply.

Is there any issue with the previous implementation using visibility sensor? Why was the migration done exactly?

Should I be downgrading and using it then?

**Comment by payapula** [comment]
Hi @crushy26 

I am not sure if it caused any issues, however the reason for change is mentioned in this issue - [#63](https://github.com/stephane-monnot/react-vertical-timeline/issues/63) and corresponding PR - [#67](https://github.com/stephane-monnot/react-vertical-timeline/pull/67)

Sure you can downgrade and give it a shot. I guess there should not be any problem.

**Comment by crushy26** [comment]
Hi @payapula 

So far everything is working as expected. Thank you.

**Comment by parvathirajan** [comment]
So is that solved with 2.2.0? @crushy26

**Comment by crushy26** [comment]
Yes  it was solved with downgrade

**Comment by parvathirajan** [comment]
Hi.. Thank you so much Stephane. 🎉 That's really perfect fix. 😀 Sorry for the delayed response.

Sure I'll keep that in mind. Will replace my name everywhere 😹
